'use client'
import { useState, useEffect } from 'react'
import { Package, AlertTriangle, Plus, ArrowDown, ArrowUp, MapPin, RefreshCw } from 'lucide-react'
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts'
import { PageHeader, Card, StatCard, Badge, Table, Tabs, Button, EmptyState, ProgressBar } from '@/components/ui'

type InventoryItem = { id: string; sku: string; name: string; warehouse: string; binLocation?: string; onHand: number; available: number; reserved: number; reorderPoint: number; reorderQty: number; value: number; status: 'ok' | 'low_stock' | 'out_of_stock'; avgCost?: number }
type Movement = { id: string; product: string; type: string; quantity: number; warehouse: string; reference?: string; createdAt: string }
type PO = { id: string; number: string; vendor?: string; status: string; total: number; expectedDate?: string; createdAt: string; autoGenerated: boolean }
type Stats = { totalSkus: number; lowStockCount: number; outOfStockCount: number; totalInventoryValue: number; pendingPOs: number }

const fmtMoney = (c: number) => `$${(c/100).toLocaleString()}`
const fmtDate = (d?: string) => d ? new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : '—'

export default function InventoryModule() {
  const [tab, setTab] = useState('stock')
  const [items, setItems] = useState<InventoryItem[]>([])
  const [movements, setMovements] = useState<Movement[]>([])
  const [pos, setPOs] = useState<PO[]>([])
  const [stats, setStats] = useState<Stats | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.all([
      fetch('/api/erp?view=inventory').then(r => r.ok ? r.json() : { items: [] }),
      fetch('/api/erp?view=movements').then(r => r.ok ? r.json() : { movements: [] }),
      fetch('/api/erp?view=purchase_orders').then(r => r.ok ? r.json() : { orders: [] }),
      fetch('/api/erp?view=inventory_stats').then(r => r.ok ? r.json() : {}),
    ]).then(([inv, mv, po, s]) => {
      setItems(inv.items || []); setMovements(mv.movements || [])
      setPOs(po.orders || []); setStats(s)
      setLoading(false)
    })
  }, [])

  const lowStock = items.filter(i => i.status === 'low_stock')
  const outOfStock = items.filter(i => i.status === 'out_of_stock')

  const topValueItems = [...items].sort((a, b) => b.value - a.value).slice(0, 8)
  const chartData = topValueItems.map(i => ({ name: i.name.substring(0, 15), value: i.value / 100 }))

  return (
    <div className="h-full flex flex-col">
      <PageHeader
        title="Inventory & WMS"
        subtitle="Stock levels, warehouse management, purchase orders, and AI-powered reordering"
        actions={
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" icon={RefreshCw}>Sync</Button>
            <Button size="sm" icon={Plus}>Add Product</Button>
          </div>
        }
      />

      {stats && stats.totalSkus !== undefined && (
        <div className="grid grid-cols-5 gap-3 p-4 border-b border-black/[0.07] bg-gray-50">
          <StatCard label="Total SKUs" value={stats.totalSkus.toLocaleString()} color="#2563eb" />
          <StatCard label="Inventory Value" value={fmtMoney(stats.totalInventoryValue)} color="#7c3aed" />
          <StatCard label="Low Stock" value={stats.lowStockCount.toString()} sub="at or below reorder point" color="#d97706" icon={AlertTriangle} />
          <StatCard label="Out of Stock" value={stats.outOfStockCount.toString()} sub="needs immediate action" color="#dc2626" icon={AlertTriangle} />
          <StatCard label="Pending POs" value={stats.pendingPOs.toString()} sub="purchase orders" color="#0891b2" />
        </div>
      )}

      {/* Alert bar */}
      {(lowStock.length > 0 || outOfStock.length > 0) && (
        <div className="px-4 py-2 bg-red-50 border-b border-red-100 flex items-center gap-3">
          <AlertTriangle size={14} className="text-red-500 flex-shrink-0" />
          <span className="text-sm text-red-700">
            {outOfStock.length > 0 && <strong>{outOfStock.length} SKUs out of stock</strong>}
            {outOfStock.length > 0 && lowStock.length > 0 && ' · '}
            {lowStock.length > 0 && <span>{lowStock.length} SKUs below reorder point</span>}
            . AI has auto-generated purchase orders — check CommandInbox.
          </span>
        </div>
      )}

      <Tabs tabs={[
        { key: 'stock', label: 'Stock Levels', count: items.length },
        { key: 'movements', label: 'Movements', count: movements.length },
        { key: 'purchase_orders', label: 'Purchase Orders', count: pos.length },
        { key: 'analytics', label: 'Analytics' },
      ]} active={tab} onChange={setTab} />

      <div className="flex-1 overflow-auto p-4">
        {tab === 'stock' && (
          <Card padding={false}>
            <Table<InventoryItem>
              columns={[
                { key: 'sku', header: 'SKU', render: r => <span className="font-mono text-xs text-gray-500">{r.sku}</span> },
                { key: 'name', header: 'Product', render: r => <span className="font-medium text-sm text-gray-900">{r.name}</span> },
                { key: 'warehouse', header: 'Location', render: r => (
                  <div className="text-xs text-gray-500">
                    <div className="flex items-center gap-1"><Package size={10}/>{r.warehouse}</div>
                    {r.binLocation && <div className="flex items-center gap-1"><MapPin size={10}/>{r.binLocation}</div>}
                  </div>
                )},
                { key: 'stock', header: 'Stock', render: r => (
                  <div>
                    <div className="font-bold text-sm">{r.onHand} units</div>
                    <div className="text-xs text-gray-400">{r.available} available · {r.reserved} reserved</div>
                    <div className="mt-1">
                      <ProgressBar value={r.onHand} max={Math.max(r.reorderQty * 2, r.onHand + 1)} color={r.status === 'out_of_stock' ? '#dc2626' : r.status === 'low_stock' ? '#d97706' : '#00a855'} />
                    </div>
                  </div>
                )},
                { key: 'reorder', header: 'Reorder', render: r => (
                  <div className="text-xs text-gray-500">
                    <div>Point: {r.reorderPoint}</div>
                    <div>Qty: {r.reorderQty}</div>
                  </div>
                )},
                { key: 'value', header: 'Value', render: r => <span className="font-semibold text-sm tabular-nums">{fmtMoney(r.value)}</span> },
                { key: 'status', header: 'Status', render: r => (
                  <Badge variant={r.status === 'ok' ? 'green' : r.status === 'low_stock' ? 'yellow' : 'red'}>
                    {r.status === 'ok' ? 'In Stock' : r.status === 'low_stock' ? 'Low Stock' : 'Out of Stock'}
                  </Badge>
                )},
              ]}
              data={items}
              emptyMessage="No products yet. Add products or sync from your eCommerce platform."
            />
          </Card>
        )}

        {tab === 'movements' && (
          <Card padding={false}>
            <Table<Movement>
              columns={[
                { key: 'product', header: 'Product', render: r => <span className="font-medium text-sm">{r.product}</span> },
                { key: 'type', header: 'Type', render: r => (
                  <div className="flex items-center gap-1.5">
                    {r.quantity > 0 ? <ArrowDown size={12} className="text-[#00a855]" /> : <ArrowUp size={12} className="text-red-500" />}
                    <Badge variant={r.type === 'receipt' ? 'green' : r.type === 'shipment' ? 'red' : 'blue'}>{r.type}</Badge>
                  </div>
                )},
                { key: 'quantity', header: 'Qty', render: r => (
                  <span className={`font-bold tabular-nums ${r.quantity > 0 ? 'text-[#00a855]' : 'text-red-500'}`}>
                    {r.quantity > 0 ? '+' : ''}{r.quantity}
                  </span>
                )},
                { key: 'warehouse', header: 'Warehouse', render: r => <span className="text-sm text-gray-500">{r.warehouse}</span> },
                { key: 'reference', header: 'Reference', render: r => r.reference ? <span className="font-mono text-xs text-gray-500">{r.reference}</span> : <span className="text-gray-300">—</span> },
                { key: 'createdAt', header: 'Date', render: r => <span className="text-xs text-gray-400">{fmtDate(r.createdAt)}</span> },
              ]}
              data={movements}
              emptyMessage="No inventory movements yet."
            />
          </Card>
        )}

        {tab === 'purchase_orders' && (
          <Card padding={false}>
            <Table<PO>
              columns={[
                { key: 'number', header: 'PO #', render: r => (
                  <div>
                    <span className="font-mono text-sm">{r.number}</span>
                    {r.autoGenerated && <Badge variant="blue" >AI Auto</Badge>}
                  </div>
                )},
                { key: 'vendor', header: 'Vendor', render: r => <span className="text-sm text-gray-700">{r.vendor || '—'}</span> },
                { key: 'total', header: 'Total', render: r => <span className="font-semibold tabular-nums">{fmtMoney(r.total)}</span> },
                { key: 'status', header: 'Status', render: r => (
                  <Badge variant={r.status === 'RECEIVED' ? 'green' : r.status === 'SENT' ? 'blue' : r.status === 'CANCELLED' ? 'red' : 'yellow'}>
                    {r.status.toLowerCase().replace('_', ' ')}
                  </Badge>
                )},
                { key: 'expectedDate', header: 'Expected', render: r => <span className="text-sm text-gray-500">{fmtDate(r.expectedDate)}</span> },
                { key: 'createdAt', header: 'Created', render: r => <span className="text-xs text-gray-400">{fmtDate(r.createdAt)}</span> },
              ]}
              data={pos}
              emptyMessage="No purchase orders. AI will auto-generate POs when stock hits reorder points."
            />
          </Card>
        )}

        {tab === 'analytics' && chartData.length > 0 && (
          <Card>
            <h3 className="font-bold text-gray-900 mb-4">Inventory Value by Product</h3>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={chartData} layout="vertical">
                <XAxis type="number" tickFormatter={v => `$${v.toLocaleString()}`} tick={{ fontSize: 11 }} />
                <YAxis type="category" dataKey="name" tick={{ fontSize: 11 }} width={120} />
                <Tooltip formatter={(v: number) => `$${v.toLocaleString()}`} />
                <Bar dataKey="value" fill="#2563eb" radius={[0, 4, 4, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </Card>
        )}
      </div>
    </div>
  )
}
