import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@clerk/nextjs/server'
import { db } from '@/lib/db'
import { ERPAgent } from '@/lib/ai/erp'

export async function GET(req: NextRequest) {
  const { orgId, userId } = await auth()
  const id = orgId || userId
  if (!id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const business = await db.business.findUnique({ where: { clerkOrgId: id } })
  if (!business) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const view = new URL(req.url).searchParams.get('view') || 'inventory'

  if (view === 'inventory') {
    const items = await db.inventoryItem.findMany({
      where: { businessId: business.id },
      include: { product: true, warehouse: true },
      orderBy: { available: 'asc' },
    })
    return NextResponse.json({
      items: items.map(i => ({
        id: i.id, sku: i.product.sku, name: i.product.name,
        warehouse: i.warehouse.name, binLocation: i.binLocation,
        onHand: i.onHand, available: i.available, reserved: i.reserved,
        reorderPoint: i.reorderPoint, reorderQty: i.reorderQty,
        value: i.onHand * i.product.unitCost, avgCost: i.avgCost,
        status: i.onHand === 0 ? 'out_of_stock' : i.available <= i.reorderPoint ? 'low_stock' : 'ok',
      })),
    })
  }

  if (view === 'movements') {
    const movements = await db.inventoryMovement.findMany({
      where: { businessId: business.id },
      include: { item: { include: { product: true } }, warehouse: true },
      orderBy: { createdAt: 'desc' },
      take: 100,
    })
    return NextResponse.json({
      movements: movements.map(m => ({
        id: m.id, product: m.item.product.name, type: m.type,
        quantity: m.quantity, warehouse: m.warehouse.name,
        reference: m.reference, createdAt: m.createdAt,
      })),
    })
  }

  if (view === 'purchase_orders') {
    const orders = await db.purchaseOrder.findMany({
      where: { businessId: business.id },
      include: { vendor: true },
      orderBy: { createdAt: 'desc' },
      take: 50,
    })
    return NextResponse.json({
      orders: orders.map(o => ({
        id: o.id, number: o.number, vendor: o.vendor?.name,
        status: o.status, total: o.total, expectedDate: o.expectedDate,
        createdAt: o.createdAt, autoGenerated: o.autoGenerated,
      })),
    })
  }

  if (view === 'sales_orders') {
    const orders = await db.salesOrder.findMany({
      where: { businessId: business.id },
      include: { contact: true, company: true },
      orderBy: { createdAt: 'desc' },
      take: 50,
    })
    return NextResponse.json({ orders })
  }

  if (view === 'inventory_stats') {
    const agent = new ERPAgent(business.id)
    return NextResponse.json(await agent.getInventorySummary())
  }

  return NextResponse.json({ error: 'Invalid view' }, { status: 400 })
}

export async function POST(req: NextRequest) {
  const { orgId, userId } = await auth()
  const id = orgId || userId
  if (!id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const business = await db.business.findUnique({ where: { clerkOrgId: id } })
  if (!business) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const { action, ...data } = await req.json()
  const agent = new ERPAgent(business.id)

  if (action === 'check_reorders') return NextResponse.json({ triggered: await agent.checkReorderPoints() })
  if (action === 'receive_inventory') return NextResponse.json({ success: true, result: await agent.receiveInventory(data.poId, data.lines) })
  if (action === 'fulfill_order') return NextResponse.json({ success: true, result: await agent.fulfillOrder(data.orderId) })

  return NextResponse.json({ error: 'Unknown action' }, { status: 400 })
}
