import Anthropic from '@anthropic-ai/sdk'
import { db } from '@/lib/db'
import { createAiAction } from '@/lib/ai/actions'
import { recordSaving } from '@/lib/ai/savings'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! })

export class ERPAgent {
  private businessId: string
  constructor(b: string) { this.businessId = b }

  // Check inventory levels and trigger reorders
  async checkReorderPoints(): Promise<number> {
    const lowStock = await db.inventoryItem.findMany({
      where: {
        businessId: this.businessId,
        available: { lte: db.inventoryItem.fields.reorderPoint as unknown as number },
      },
      include: { product: true, warehouse: true },
    })

    // Workaround: manual query
    const items = await db.$queryRaw<Array<{
      id: string; productId: string; warehouseId: string;
      available: number; reorderPoint: number; reorderQty: number;
      productName: string; unitCost: number; warehouseName: string;
    }>>`
      SELECT i.id, i."productId", i."warehouseId",
             i.available, i."reorderPoint", i."reorderQty",
             p.name as "productName", p."unitCost",
             w.name as "warehouseName"
      FROM inventory_items i
      JOIN products p ON p.id = i."productId"
      JOIN warehouses w ON w.id = i."warehouseId"
      WHERE i."businessId" = ${this.businessId}
        AND i.available <= i."reorderPoint"
    `

    let triggered = 0
    for (const item of items) {
      await this.createPurchaseOrderForItem(item)
      triggered++
    }

    return triggered
  }

  private async createPurchaseOrderForItem(item: {
    id: string; productId: string; warehouseId: string;
    available: number; reorderPoint: number; reorderQty: number;
    productName: string; unitCost: number; warehouseName: string;
  }): Promise<void> {
    const total = item.reorderQty * item.unitCost

    // Find preferred vendor from recent POs
    const lastPO = await db.purchaseOrder.findFirst({
      where: { businessId: this.businessId },
      include: { lines: { where: { productId: item.productId } }, vendor: true },
      orderBy: { createdAt: 'desc' },
    })

    const po = await db.purchaseOrder.create({
      data: {
        businessId: this.businessId,
        vendorId: lastPO?.vendorId,
        number: `PO-${Date.now()}`,
        subtotal: total,
        total,
        autoGenerated: true,
        aiReasoning: `Stock level ${item.available} units is at/below reorder point ${item.reorderPoint}. Reordering ${item.reorderQty} units.`,
        lines: {
          create: {
            productId: item.productId,
            inventoryItemId: item.id,
            description: item.productName,
            quantity: item.reorderQty,
            unitCost: item.unitCost,
            total,
          },
        },
      },
    })

    const action = await createAiAction({
      businessId: this.businessId,
      module: 'SUPPLY_CHAIN',
      actionType: 'create_purchase_order',
      title: `Auto-PO: ${item.productName}`,
      description: `Stock at ${item.available}/${item.reorderPoint} reorder point. Auto-generated PO for ${item.reorderQty} units from ${lastPO?.vendor?.name || 'preferred vendor'}.`,
      payload: { poId: po.id, productId: item.productId, quantity: item.reorderQty },
      requiresApproval: total > 20000, // require approval if > $200
      approvalReason: total > 20000 ? 'Purchase order exceeds auto-approve threshold' : undefined,
      amount: total,
      status: total > 20000 ? 'PENDING_APPROVAL' : 'COMPLETED',
    })

    if (total > 20000) {
      await db.inboxItem.create({
        data: {
          businessId: this.businessId,
          actionId: action.id,
          title: `Approve PO: ${item.productName} × ${item.reorderQty} units`,
          description: `$${(total / 100).toFixed(0)} from ${lastPO?.vendor?.name || 'vendor'}. Stock: ${item.available} left (reorder at ${item.reorderPoint}).`,
          module: 'SUPPLY_CHAIN',
          urgency: item.available === 0 ? 'CRITICAL' : 'NORMAL',
          amount: total,
        },
      })
    }
  }

  // Update inventory after receiving PO
  async receiveInventory(poId: string, receivedLines: { lineId: string; qty: number }[]): Promise<void> {
    const po = await db.purchaseOrder.findUniqueOrThrow({
      where: { id: poId },
      include: { lines: true },
    })

    for (const received of receivedLines) {
      const line = po.lines.find(l => l.id === received.lineId)
      if (!line?.inventoryItemId) continue

      // Update inventory
      await db.inventoryItem.update({
        where: { id: line.inventoryItemId },
        data: {
          onHand: { increment: received.qty },
          available: { increment: received.qty },
        },
      })

      // Record movement
      await db.inventoryMovement.create({
        data: {
          businessId: this.businessId,
          itemId: line.inventoryItemId,
          warehouseId: (await db.inventoryItem.findUniqueOrThrow({ where: { id: line.inventoryItemId! } })).warehouseId,
          type: 'receipt',
          quantity: received.qty,
          cost: line.unitCost,
          reference: po.number,
        },
      })

      // Update received qty on line
      await db.purchaseOrderLine.update({
        where: { id: line.id },
        data: { receivedQty: { increment: received.qty } },
      })
    }

    // Update PO status
    const updatedLines = await db.purchaseOrderLine.findMany({ where: { poId } })
    const allReceived = updatedLines.every(l => l.receivedQty >= l.quantity)
    const partialReceived = updatedLines.some(l => l.receivedQty > 0)

    await db.purchaseOrder.update({
      where: { id: poId },
      data: {
        status: allReceived ? 'RECEIVED' : partialReceived ? 'PARTIALLY_RECEIVED' : po.status,
        receivedDate: allReceived ? new Date() : undefined,
      },
    })
  }

  // Fulfill sales order — pick, pack, ship
  async fulfillOrder(orderId: string): Promise<void> {
    const order = await db.salesOrder.findUniqueOrThrow({
      where: { id: orderId },
      include: { lines: { include: { product: true } } },
    })

    for (const line of order.lines) {
      if (!line.productId) continue

      // Find inventory
      const item = await db.inventoryItem.findFirst({
        where: { productId: line.productId, businessId: this.businessId },
      })
      if (!item) continue

      if (item.available < line.quantity) {
        // Trigger reorder
        await this.createPurchaseOrderForItem({
          id: item.id, productId: item.productId, warehouseId: item.warehouseId,
          available: item.available, reorderPoint: item.reorderPoint, reorderQty: Math.max(item.reorderQty, line.quantity),
          productName: line.product?.name || 'Product', unitCost: line.product?.unitCost || 0,
          warehouseName: 'Default',
        })
        continue
      }

      // Deduct inventory
      await db.inventoryItem.update({
        where: { id: item.id },
        data: {
          onHand: { decrement: line.quantity },
          available: { decrement: line.quantity },
        },
      })

      await db.inventoryMovement.create({
        data: {
          businessId: this.businessId,
          itemId: item.id,
          warehouseId: item.warehouseId,
          type: 'shipment',
          quantity: -line.quantity,
          reference: order.number,
        },
      })

      await db.salesOrderLine.update({
        where: { id: line.id },
        data: { fulfilledQty: { increment: line.quantity } },
      })
    }

    const allFulfilled = (await db.salesOrderLine.findMany({ where: { orderId } }))
      .every(l => l.fulfilledQty >= l.quantity)

    if (allFulfilled) {
      await db.salesOrder.update({ where: { id: orderId }, data: { status: 'SHIPPED', shipDate: new Date() } })
    }
  }

  // AI-powered demand forecasting
  async forecastDemand(productId: string, days = 90): Promise<{ units: number; confidence: number }> {
    const movements = await db.inventoryMovement.findMany({
      where: {
        businessId: this.businessId,
        item: { productId },
        type: 'shipment',
        createdAt: { gte: new Date(Date.now() - 180 * 86400000) },
      },
      orderBy: { createdAt: 'asc' },
    })

    const totalUnits = Math.abs(movements.reduce((s, m) => s + m.quantity, 0))
    const dailyAvg = totalUnits / 180
    const projected = Math.ceil(dailyAvg * days * 1.1) // 10% buffer

    return { units: projected, confidence: movements.length > 10 ? 0.85 : 0.5 }
  }

  // Inventory summary for dashboard
  async getInventorySummary() {
    const [totalItems, lowStock, outOfStock, totalValue] = await Promise.all([
      db.inventoryItem.count({ where: { businessId: this.businessId } }),
      db.$queryRaw<[{ count: bigint }]>`
        SELECT COUNT(*) as count FROM inventory_items
        WHERE "businessId" = ${this.businessId} AND available <= "reorderPoint" AND available > 0
      `,
      db.inventoryItem.count({ where: { businessId: this.businessId, onHand: 0 } }),
      db.$queryRaw<[{ total: bigint }]>`
        SELECT COALESCE(SUM(i."onHand" * p."unitCost"), 0) as total
        FROM inventory_items i JOIN products p ON p.id = i."productId"
        WHERE i."businessId" = ${this.businessId}
      `,
    ])

    const pendingPOs = await db.purchaseOrder.count({
      where: { businessId: this.businessId, status: { in: ['DRAFT', 'SENT', 'CONFIRMED'] } },
    })

    return {
      totalSkus: totalItems,
      lowStockCount: Number(lowStock[0]?.count || 0),
      outOfStockCount: outOfStock,
      totalInventoryValue: Number(totalValue[0]?.total || 0),
      pendingPOs,
    }
  }
}
